# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bonda/test/whisper-alsa

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bonda/test/whisper-alsa

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bonda/test/whisper-alsa/CMakeFiles /home/bonda/test/whisper-alsa//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bonda/test/whisper-alsa/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named whisper-alsa

# Build rule for target.
whisper-alsa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 whisper-alsa
.PHONY : whisper-alsa

# fast build rule for target.
whisper-alsa/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper-alsa.dir/build.make CMakeFiles/whisper-alsa.dir/build
.PHONY : whisper-alsa/fast

capture.o: capture.cpp.o
.PHONY : capture.o

# target to build an object file
capture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper-alsa.dir/build.make CMakeFiles/whisper-alsa.dir/capture.cpp.o
.PHONY : capture.cpp.o

capture.i: capture.cpp.i
.PHONY : capture.i

# target to preprocess a source file
capture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper-alsa.dir/build.make CMakeFiles/whisper-alsa.dir/capture.cpp.i
.PHONY : capture.cpp.i

capture.s: capture.cpp.s
.PHONY : capture.s

# target to generate assembly for a file
capture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper-alsa.dir/build.make CMakeFiles/whisper-alsa.dir/capture.cpp.s
.PHONY : capture.cpp.s

log.o: log.cpp.o
.PHONY : log.o

# target to build an object file
log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper-alsa.dir/build.make CMakeFiles/whisper-alsa.dir/log.cpp.o
.PHONY : log.cpp.o

log.i: log.cpp.i
.PHONY : log.i

# target to preprocess a source file
log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper-alsa.dir/build.make CMakeFiles/whisper-alsa.dir/log.cpp.i
.PHONY : log.cpp.i

log.s: log.cpp.s
.PHONY : log.s

# target to generate assembly for a file
log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper-alsa.dir/build.make CMakeFiles/whisper-alsa.dir/log.cpp.s
.PHONY : log.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper-alsa.dir/build.make CMakeFiles/whisper-alsa.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper-alsa.dir/build.make CMakeFiles/whisper-alsa.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper-alsa.dir/build.make CMakeFiles/whisper-alsa.dir/main.cpp.s
.PHONY : main.cpp.s

transcriber.o: transcriber.cpp.o
.PHONY : transcriber.o

# target to build an object file
transcriber.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper-alsa.dir/build.make CMakeFiles/whisper-alsa.dir/transcriber.cpp.o
.PHONY : transcriber.cpp.o

transcriber.i: transcriber.cpp.i
.PHONY : transcriber.i

# target to preprocess a source file
transcriber.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper-alsa.dir/build.make CMakeFiles/whisper-alsa.dir/transcriber.cpp.i
.PHONY : transcriber.cpp.i

transcriber.s: transcriber.cpp.s
.PHONY : transcriber.s

# target to generate assembly for a file
transcriber.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper-alsa.dir/build.make CMakeFiles/whisper-alsa.dir/transcriber.cpp.s
.PHONY : transcriber.cpp.s

whisper.o: whisper.cpp.o
.PHONY : whisper.o

# target to build an object file
whisper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper-alsa.dir/build.make CMakeFiles/whisper-alsa.dir/whisper.cpp.o
.PHONY : whisper.cpp.o

whisper.i: whisper.cpp.i
.PHONY : whisper.i

# target to preprocess a source file
whisper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper-alsa.dir/build.make CMakeFiles/whisper-alsa.dir/whisper.cpp.i
.PHONY : whisper.cpp.i

whisper.s: whisper.cpp.s
.PHONY : whisper.s

# target to generate assembly for a file
whisper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper-alsa.dir/build.make CMakeFiles/whisper-alsa.dir/whisper.cpp.s
.PHONY : whisper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... whisper-alsa"
	@echo "... capture.o"
	@echo "... capture.i"
	@echo "... capture.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... transcriber.o"
	@echo "... transcriber.i"
	@echo "... transcriber.s"
	@echo "... whisper.o"
	@echo "... whisper.i"
	@echo "... whisper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

